### ISSUE TITLE
OnRefresh not called

### ISSUE THREAD

**Issue by pkshetlie** [BUTR/Bannerlord.UIExtenderEx#12]
Hi, i'm new in modding I used shdwp/UIExtenderLib and now migrate to your solution, I have only one thing that I can't make work it's the OnRefresh() method that is never called.

```csharp
[ViewModelMixin]
public class MapInfoMixin : BaseViewModelMixin<MapInfoVM>
{
    public MapInfoMixin(MapInfoVM vm) : base(vm { }

    public override void OnRefresh()
    {
         // nerver get in :(
    }
}
```

PS sorry for my bad english, nd sorry if it's the wrong place to ask that.

**Comment by Aragas** [comment]
Yo!
Good catch! UIExtenderEx has the UIExtender's method of setting the `Refresh` method.
You need to specify the name of the Refresh method in the attribute, i.e.
```csharp
[ViewModelMixin("Refresh")] // or [ViewModelMixin(nameof(MapInfoVM.Refresh))] 
public class MapInfoMixin : BaseViewModelMixin<MapInfoVM>
```

**Comment by Aragas** [comment]
It is done like this because the ViewModels might have slightly different names for the conceptual 'Refresh' method. It could be `Refresh`, `OnRefresh` or have any other name.

**Comment by pkshetlie** [comment]
thank you so much !
