### ISSUE TITLE
can the Index use negative numbers?

### ISSUE THREAD

**Issue by l4dfire** [BUTR/Bannerlord.UIExtenderEx#271]
just like the syntax of Golang or Python
when set index=>-2,  expect to insert the node into the penultimate position.

**Comment by Aragas** [comment]
I don't believe so! In C#, the index variable is expected to be a non negative number.
The alternative is the `System.Index` operator that was introduced in the newer version of C# - it's format is like this `^2` will mean second from last.
UIExtenderEx might not support this currently out of the box. I quickly checked the API and hadn't found a way to do that

**Comment by l4dfire** [comment]
Okay, I hope UIExtenderEx can implement the functionality of specifying the Nth element from the end soon.
