### ISSUE TITLE
UIExtenderEx.Register() is obsolete, invalidating doc examples and example projects

### ISSUE THREAD

**Issue by ninchistudios** [BUTR/Bannerlord.UIExtenderEx#6]
I think the code solution is to change to: `_extender.Register(Assembly.GetCallingAssembly());`

it might be worth updating the tutorial, thanks

**Comment by Aragas** [comment]
Thanks for the report! While ``Assembly.GetCallingAssembly()`` is an acceptable solution, it might provide the wrong assembly if the ``Register()`` method is executed in a lambda, for example.
